services:
  acceralytdevtest:
    image: acceralytdevtest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Host=db;Database=secureelasticdb;Username=admin;Password=admin123
      - Elasticsearch__Uri=http://elasticsearch:9200
      - Serilog__WriteTo__0__Name=File
      - Serilog__WriteTo__0__Args__path=/app/logs/log.txt
    ports:
      - "5000:80"
    depends_on:
      - db
      - elasticsearch

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: secureelasticdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:15432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data:
